-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 21:49:57 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema quantumine
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quantumine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quantumine` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `quantumine` ;

-- -----------------------------------------------------
-- Table `quantumine`.`train_number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quantumine`.`train_number` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` INT(1) NOT NULL DEFAULT 1,
  `number` VARCHAR(10) NOT NULL,
  `origin_city_id` INT NOT NULL,
  `origin_time` INT NOT NULL,
  `terminal_city_id` INT NOT NULL,
  `terminal_time` INT NOT NULL,
  `duration` INT NOT NULL,
  `shangwu_seat_count` INT NOT NULL,
  `yideng_seat_count` INT NOT NULL,
  `erdeng_seat_count` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantumine`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quantumine`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` INT(1) NOT NULL DEFAULT 1,
  `name_chinese` VARCHAR(45) NOT NULL,
  `name_pinyin` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantumine`.`train_number_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quantumine`.`train_number_city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` INT(1) NOT NULL DEFAULT 1,
  `train_number_id` INT NOT NULL,
  `start_city_id` INT NOT NULL,
  `start_time` INT NOT NULL,
  `end_city_id` INT NOT NULL,
  `end_time` INT NOT NULL,
  `stay_minutes` INT NOT NULL,
  `duration` INT NOT NULL,
  `shangwu_seat_count` INT NOT NULL,
  `shangwu_seat_price` DOUBLE NOT NULL,
  `yideng_seat_count` INT NOT NULL,
  `yideng_seat_price` DOUBLE NOT NULL,
  `erdeng_seat_count` INT NOT NULL,
  `erdeng_seat_price` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `train_number_id_idx` (`train_number_id` ASC),
  INDEX `start_city_id_idx` (`start_city_id` ASC),
  INDEX `end_city_id_idx` (`end_city_id` ASC),
  CONSTRAINT `train_number_id`
    FOREIGN KEY (`train_number_id`)
    REFERENCES `quantumine`.`train_number` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `start_city_id`
    FOREIGN KEY (`start_city_id`)
    REFERENCES `quantumine`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `end_city_id`
    FOREIGN KEY (`end_city_id`)
    REFERENCES `quantumine`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantumine`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quantumine`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` INT(1) NOT NULL DEFAULT 1,
  `real_name` VARCHAR(45) NOT NULL,
  `gender` INT(1) NOT NULL,
  `personal_id_number` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NULL,
  `login_name` VARCHAR(45) NOT NULL,
  `login_email` VARCHAR(45) NOT NULL,
  `login_password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `quantumine`.`train_number_city_daily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quantumine`.`train_number_city_daily` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` INT(1) NOT NULL DEFAULT 1,
  `train_number_city_id` INT NOT NULL,
  `date` INT NOT NULL,
  `shangwu_seat_left_count` INT NULL,
  `yideng_seat_left_count` INT NULL,
  `erdeng_seat_left_count` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `tnci_idx` (`train_number_city_id` ASC),
  CONSTRAINT `tnci`
    FOREIGN KEY (`train_number_city_id`)
    REFERENCES `quantumine`.`train_number_city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ----------
-- data
-- ----------
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60001', '1', '70001', '10001', '800', '10002', '820', '2', '20', '20', '121.5', '110', '59.5', '480', '39.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60002', '1', '70001', '10001', '800', '10003', '835', '2', '35', '20', '154.5', '110', '84.5', '480', '49.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60003', '1', '70001', '10001', '800', '10004', '855', '2', '55', '20', '239.5', '110', '119.5', '480', '74.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60004', '1', '70001', '10001', '800', '10005', '910', '2', '70', '20', '344.5', '110', '174.5', '480', '109.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60005', '1', '70001', '10001', '800', '10006', '930', '2', '90', '20', '429.5', '110', '229.5', '480', '134.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60006', '1', '70001', '10001', '800', '10007', '1030', '2', '150', '20', '889', '110', '474', '480', '279');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60007', '1', '70001', '10001', '800', '10008', '1330', '2', '330', '20', '1748', '110', '933', '480', '553');

INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60008', '1', '70001', '10002', '822', '10003', '835', '2', '13', '20', '60.5', '110', '29.5', '480', '19.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60009', '1', '70001', '10002', '822', '10004', '855', '2', '33', '20', '117.5', '110', '59.5', '480', '34.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60010', '1', '70001', '10002', '822', '10005', '910', '2', '48', '20', '222.5', '110', '114.5', '480', '69.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60011', '1', '70001', '10002', '822', '10006', '930', '2', '68', '20', '309.5', '110', '164.5', '480', '99.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60012', '1', '70001', '10002', '822', '10007', '1030', '2', '128', '20', '784', '110', '419', '480', '249');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60013', '1', '70001', '10002', '822', '20001', '1330', '2', '308', '20', '1653.5', '110', '883.5', '480', '523.5');

INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60014', '1', '70001', '10003', '837', '10004', '855', '2', '18', '20', '56.5', '110', '29.5', '480', '19.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60015', '1', '70001', '10003', '837', '10005', '910', '2', '33', '20', '174.5', '110', '94.5', '480', '54.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60016', '1', '70001', '10003', '837', '10006', '930', '2', '53', '20', '268.5', '110', '134.5', '480', '84.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60017', '1', '70001', '10003', '837', '10007', '1030', '2', '113', '20', '749', '110', '399', '480', '239');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60018', '1', '70001', '10003', '837', '20001', '1330', '2', '293', '20', '1618.5', '110', '863.5', '480', '513.5');

INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60019', '1', '70001', '10004', '857', '10005', '910', '2', '13', '20', '104.5', '110', '54.5', '480', '34.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60020', '1', '70001', '10004', '857', '10006', '930', '2', '33', '20', '227.5', '110', '114.5', '480', '69.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60021', '1', '70001', '10004', '857', '10007', '1030', '2', '93', '20', '669', '110', '354', '480', '209');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60022', '1', '70001', '10004', '857', '20001', '1330', '2', '273', '20', '1553.5', '110', '828.5', '480', '493.5');

INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60023', '1', '70001', '10005', '912', '10006', '930', '2', '18', '20', '94.5', '110', '49.5', '480', '29.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60024', '1', '70001', '10005', '912', '10007', '1030', '2', '78', '20', '574.5', '110', '304.5', '480', '179.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60025', '1', '70001', '10005', '912', '20001', '1330', '2', '258', '20', '1478.5', '110', '788.5', '480', '468.5');

INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60026', '1', '70001', '10006', '932', '10007', '1030', '2', '58', '20', '479.5', '110', '254.5', '480', '149.5');
INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60027', '1', '70001', '10006', '932', '20001', '1330', '2', '238', '20', '1403.5', '110', '748.5', '480', '443.5');

INSERT INTO `quantumine`.`train_number_city` (`id`, `active`, `train_number_id`, `start_city_id`, `start_time`, `end_city_id`, `end_time`, `stay_minutes`, `duration`, `shangwu_seat_count`, `shangwu_seat_price`, `yideng_seat_count`, `yideng_seat_price`, `erdeng_seat_count`, `erdeng_seat_price`) VALUES ('60028', '1', '70001', '10007', '1032', '20001', '1330', '2', '178', '20', '974', '110', '519', '480', '309');
